---
name: Build docker image

"on":
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/**
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - patches/**
      - scripts/**

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - v3.2.15-stable-3.2-luminous
          - v4.0.20-stable-4.0-nautilus
          - v5.0.10-stable-5.0-octopus
          - v6.0.1-stable-6.0-pacific

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'
      - run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.version }}
          REPOSITORY: osism/ceph-daemon
      - run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.version }}
          REPOSITORY: osism/ceph-daemon
        if: github.ref == 'refs/heads/main'
